name: 'Hello World Docker Action'
description: 'trial'

inputs:
  who-to-greet:
    requried: true
    default: 'world'

outputs:
  time:
    description: 'The time we said hello'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}

